baseURL = ""
languageCode = "en-us"
title = "JODC"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true
disqusShortname = "jodc"
[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3


[params]
    since = 2019
    author = ""                           # Author's name
    avatar = "/mascot.png"           # Author's avatar
    subtitle = "JIIT Open Dev Circle"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">'

[params.social]
    GitHub = "JIITODC"
    Twitter = "jiitodc"
    Email   = "jiitodc@gmail.com"
    Facebook = "jiitodc"

